### ISSUE TITLE
Cannot create a consistent method resolution order (MRO) for bases Generic, StrawberryDjangoType after updating to strawberry-django 0.5

### ISSUE THREAD

**Issue by kwongtn** [blb-ventures/strawberry-django-plus#115]
Here's the stack trace:
```
[2022-09-11 03:57:18 +0000] [15] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/middlewares/debug_toolbar.py", line 149, in __acall__
    return await sync_to_async(self.process_request, thread_sensitive=False)(request)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/middlewares/debug_toolbar.py", line 152, in process_request
    response = super().__call__(request)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 48, in __call__
    if not show_toolbar(request) or DebugToolbar.is_toolbar_request(request):
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/debug_toolbar/toolbar.py", line 158, in is_toolbar_request
    resolver_match = request.resolver_match or resolve(
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/rosak/urls.py", line 25, in <module>
    from .schema import schema
  File "/code/rosak/schema.py", line 5, in <module>
    from strawberry_django_plus import gql
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/gql/__init__.py", line 47, in <module>
    from . import django
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/gql/django.py", line 17, in <module>
    from strawberry_django_plus.filters import filter
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/filters.py", line 15, in <module>
    from .type import input
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/type.py", line 342, in <module>
    class StrawberryDjangoType(Generic[_O, _M], _StraberryDjangoType):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Generic, StrawberryDjangoType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/handlers/asgi.py", line 155, in __call__
    await self.handle(scope, receive, send)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/handlers/asgi.py", line 178, in handle
    response = await self.get_response_async(request)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/handlers/base.py", line 162, in get_response_async
    response = await self._middleware_chain(request)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = await sync_to_async(
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/asgiref/sync.py", line 474, in thread_handler
    return func(*args, **kwargs)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/rosak/urls.py", line 25, in <module>
    from .schema import schema
  File "/code/rosak/schema.py", line 5, in <module>
    from strawberry_django_plus import gql
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/gql/__init__.py", line 47, in <module>
    from . import django
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/gql/django.py", line 17, in <module>
    from strawberry_django_plus.filters import filter
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/filters.py", line 15, in <module>
    from .type import input
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/type.py", line 342, in <module>
    class StrawberryDjangoType(Generic[_O, _M], _StraberryDjangoType):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Generic, StrawberryDjangoType

```

**Comment by bellini666** [comment]
Hi @kwongtn ,

It should be fixed in the 1.26 that I just made
