### ISSUE TITLE
Using CUD mutation

### ISSUE THREAD

**Issue by sanginovs** [blb-ventures/strawberry-django-plus#120]
HI @bellini666 
I had question about using **CUD** mutations in a non-relay context. It seems like **gql.django.update_mutation** takes Relay- specific **Type[NodeInput]**.. Since i am not using Relay, is it possible to use this helper method in a non-relay context. I tried doing this:

```

@gql.django.input(Vehicle)
class VehicleInput:
    vin: gql.auto
    year: gql.auto
    
    
update_vehicle_full: VehicleType = gql.django.update_mutation(VehicleInput)
```

but it throws this error because i am not inheriting **gql.NodeInput** which is Relay related concept:

```
{
  "data": null,
  "errors": [
    {
      "message": "'pk'",
      "locations": [
        {
          "line": 33,
          "column": 3
        }
      ],
      "path": [
        "updateVehicleFull"
      ]
    }
  ]
}
```

Any idea on how to make this work in non-relay environment?

**Comment by sanginovs** [comment]
looking at this code, it seems like first you're trying to get **id** from input (since django models generate ID as primary key). Since my model doesn't have ID field (because i set one of my custom fields as primary key), this results in UNSET. Then it will try to pop `pk = vdata.pop("pk")` and throws the above error. 
![Screen Shot 2022-09-25 at 3 51 23 PM](https://user-images.githubusercontent.com/16856287/192169150-251ef4c2-4fd0-4bad-8142-740253564983.png)

**Comment by sanginovs** [comment]
I was able to bypass this error by simply adding optional `pk` field to my VehicleInput (not Vehicle django model). 

```
@gql.django.input(Vehicle)
class VehicleInput:
    vin: gql.auto
    year: gql.auto
 ```
 
 Then i run my query like this:
 
 ```
 mutation {
  updateVehicleFull(input: {
    pk: "YS3UZ79Y476105205",
    vin:"YS3UZ79Y476105205", 
    year: 2021}) {
       __typename
    }
 ```
 
 if this is a bug, feel free to mark this issue as a bug. If not, feel free to close it. 
 Thanks

**Comment by bellini666** [comment]
Hi @sanginovs ,

The main issue here is that the `update_mutation` expects an id/pk to find the model you are trying to update.

Usually django will have a `pk` attr for each model based on the field that you define as your primary key. Do you have a model that doesn't have one? Can you explain your use case a bit more?

**Comment by sanginovs** [comment]
i have a model called **Vehicle** where vin field is a primary key because it's unique:

```
class Vehicle(models.Model):
      vin = models.CharField(max_length=17, blank=False, primary_key=True)
      year = models.IntegerField(blank=False)
```
I am trying to update one of the fields in this model. I have these types for strawberry:

```
@gql.django.type(models.Vehicle)
class VehicleType:
    vin: gql.auto
    year: gql.auto
 
 
@gql.django.input(Vehicle)
class VehicleUpdateInput:
    vin: gql.auto
    year: gql.auto
  
...  
update_vehicle_full: VehicleType = gql.django.update_mutation(VehicleUpdateInput)
```

i noticed adding **pk:gql.auto**  to **VehicleUpdateInput** won't work and throws **Vehicle** has no field named 'pk' error but adding **pk:str** will work.

**Comment by bellini666** [comment]
Hrm, that's strange because django always provide a `pk` attribute for the chosen primary key, which is a way to access it in a generic way without knowing which attr it is.

Can you provide the full traceback of the issue when using `gql.auto`?

**Comment by sanginovs** [comment]
@bellini666 sorry. i just got to this. here's the stacktrace:

'pk'

GraphQL request:33:3
32 | mutation {
33 |   updateVehicleFull(input: {vin: "jdkafshkhjsafasdh", year: 2002}) {
   |   ^
34 |     __typename
Traceback (most recent call last):
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/graphql/execution/execute.py", line 527, in execute_field
    result = resolve_fn(source, info, **args)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry_django_jwt/middleware.py", line 110, in resolve
    return _next(root, info, **kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry_django_plus/directives.py", line 119, in resolve
    return _next(root, info, *args, **kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 495, in _resolver
    return _get_result(_source, strawberry_info, **kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 487, in _get_result
    return field.get_result(
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry_django_plus/mutations/fields.py", line 212, in get_result
    return resolver(source, info, input_obj, args, kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry_django_plus/utils/aio.py", line 218, in wrapped
    raise retval
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry_django_plus/utils/aio.py", line 211, in wrapped
    retval = func(*args, **kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry_django_plus/utils/resolvers.py", line 104, in wrapper
    return resolver(*args, **kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry_django_plus/mutations/fields.py", line 268, in resolver
    pk = vdata.pop("pk")
KeyError: 'pk'
Stack (most recent call last):
  File "/var/lib/conda/envs/dalfay/lib/python3.10/threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "/var/lib/conda/envs/dalfay/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/var/lib/conda/envs/dalfay/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/servers/basehttp.py", line 178, in handle
    self.handle_one_request()
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/servers/basehttp.py", line 201, in handle_one_request
    handler.run(self.server.get_app())
  File "/var/lib/conda/envs/dalfay/lib/python3.10/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
    return self.application(environ, start_response)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry_django_jwt/decorators.py", line 284, in wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry/django/views.py", line 203, in dispatch
    result = self.schema.execute_sync(
  File "/var/lib/conda/envs/dalfay/lib/python3.10/site-packages/strawberry/schema/schema.py", line 245, in execute_sync
    self.process_errors(result.errors, execution_context=execution_context)
[25/Oct/2022 14:51:32] "POST /graphql/ HTTP/1.1" 200 120

**Comment by cpontvieux-systra** [comment]
It’s working but the `update` and `delete` function of `mutations.fields` does specify a type of `Type[NodeInput]` for `input_type`. Could you change this to `Union[type, Type[NodeInput]]` or just `type` or using two signatures with `overload`? My typing checker (mypy) is yelling on me ^_^

**Comment by bellini666** [comment]
Oh, sure! Will do that right now :)

**Comment by bellini666** [comment]
@sanginovs for curiosity, does your model not have a primary key? Because django will always create a `pk` field that is an alias to the field that is the primary key.
