### ISSUE TITLE
Unable to access model's foreign key field directly in Strawberry type

### ISSUE THREAD

**Issue by feardeers** [blb-ventures/strawberry-django-plus#133]
Example django model:
```
class CastHistory(models.Model):
    id = models.BigAutoField(primary_key=True)
    person = models.ForeignKey(
        "person.Person", on_delete=models.CASCADE, blank=True, null=True
    )
    character_name = models.CharField(max_length=200)
```

Example strawberry type class:

```
from strawberry_django_plus import gql

@gql.django.filters.filter(models.CastHistory, lookups=True)
class CastHistoryFilter:
    id: gql.ID
    person_id: gql.ID

@gql.django.type(models.CastHistory, filters=CastHistoryFilter)
class CastHistory:
    id: gql.ID
    person_id: gql.ID = gql.django.field(field_name="person_id")
    character_name: auto
```

Query:
```
query MyQuery {
  castHistoryDetails(filters: {personId: "32"}) {
    personId
    characterName
    title
  }
}
```

Result:
```
{
  "data": null,
  "errors": [
    {
      "message": "Expected code to be unreachable",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "castHistoryDetails"
      ]
    }
  ]
}
```

Expectation:
```
{
  "data": {
    "castHistoryDetails": [
      {
        "personId: "32",
        "characterName": "Arwen",
        "title": "The Lord of the Rings: The Return of the King"
      },
      {
        "personId: "32",
        "characterName": "Arwen",
        "title": "The Lord of the Rings: The Two Towers"
      },
      {
        "personId: "32",
        "characterName": "Arwen",
        "title": "The Lord of the Rings: The Fellowship of the Ring"
      }
    ]
  }
}
```

**Comment by bellini666** [comment]
Hi @feardeers ,

First of all, one thing that caught my attention is that you are using `gql.django.filters.filter` instead of `gql.django.filter`. I just noticed that I did not expose it in `__all__` =P. It is the same as the previous one, but has some fixes and improvements on top of it. Can you try it and see if you get a differente result?

Also, could you post the traceback the code generated here?

**Comment by feardeers** [comment]
Thanks for the reply. 

Switched from gql.django.filters.filter to gql.django.filter

using `strawberry-dango-plus` version 1.28.4

Here is the stack trace:

```
2022-10-18 01:12:17.386 ERROR    strawberry.execution                     127.0.0.1 --- : Expected code to be unreachable

GraphQL request:2:3
1 | query MyQuery {
2 |   castHistoryDetails(filters: {personId: "53"}) {
  |   ^
3 |     personId
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.10/site-packages/graphql/execution/execute.py", line 521, in execute_field
    result = resolve_fn(source, info, **args)
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry_django_plus/optimizer.py", line 605, in resolve
    ret = _next(root, info, *args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry/extensions/base_extension.py", line 42, in resolve
    return _next(root, info, *args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 507, in _resolver
    return _get_result(_source, strawberry_info, **kwargs)
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 499, in _get_result
    return field.get_result(
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry_django_plus/field.py", line 230, in get_result
    return resolvers.resolve_result(result, info=info, qs_resolver=qs_resolver)
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry_django_plus/utils/resolvers.py", line 286, in resolve_result
    res = ext.optimize(qs=res, info=info)
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry_django_plus/optimizer.py", line 639, in optimize
    return optimize(qs, info, config=config, store=store)
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry_django_plus/optimizer.py", line 360, in optimize
    new_store = _get_model_hints(
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry_django_plus/optimizer.py", line 179, in _get_model_hints
    for f_type_def in get_possible_type_definitions(field.type):
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry_django_plus/utils/inspect.py", line 186, in get_possible_type_definitions
    for t in get_possible_types(gql_type):
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry_django_plus/utils/inspect.py", line 166, in get_possible_types
    assert_never(gql_type)
  File "/usr/src/app/.venv/lib/python3.10/site-packages/typing_extensions.py", line 1993, in assert_never
    raise AssertionError("Expected code to be unreachable")
AssertionError: Expected code to be unreachable
Stack (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/.venv/lib/python3.10/site-packages/asgiref/sync.py", line 226, in _run_event_loop
    loop.run_until_complete(coro)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1899, in _run_once
    handle._run()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/app/.venv/lib/python3.10/site-packages/asgiref/sync.py", line 284, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry/django/views.py", line 248, in dispatch
    result = await self.schema.execute(
  File "/usr/src/app/.venv/lib/python3.10/site-packages/strawberry/schema/schema.py", line 216, in execute
    self.process_errors(result.errors, execution_context=execution_context)
█
```

**Comment by bellini666** [comment]
Hey @feardeers , I think I found the issue and it should be fixed in the release I just made: https://github.com/blb-ventures/strawberry-django-plus/releases/tag/v1.28.5

I'll close this now, but please tell me if it is not so that I can reopen it.
