### ISSUE TITLE
Async relay connection error on count()

### ISSUE THREAD

**Issue by devxoul** [blb-ventures/strawberry-django-plus#176]
Hi,
first of all, thanks for this great library.

I'm trying to define a `relay.connection` as async function in `AsyncGraphQLView`.

```py
@gql.django.type(User)
class UserNode(relay.Node):
    name: str


@strawberry.type
class Query:
    @relay.connection
    async def users(self) -> Iterable[UserNode]:
        return sync_to_async(User.objects.all)()
```

When I query the schema with the query below:

```gql
{
  users {
    edges {
      node {
      	name
      }
    }
  }
}
```

I get this error:

```
Traceback (most recent call last):
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/graphql/execution/execute.py", line 528, in await_result
    return_type, field_nodes, info, path, await result
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 525, in _async_resolver
    return await await_maybe(_get_result(_source, strawberry_info, **kwargs))
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/strawberry/utils/await_maybe.py", line 11, in await_maybe
    return await value
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/strawberry_django_plus/utils/aio.py", line 87, in resolve_async
    ret = await cast(Awaitable, ret)
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/strawberry_django_plus/utils/aio.py", line 85, in resolve_async
    ret = resolver(await value)
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/strawberry_django_plus/relay.py", line 991, in <lambda>
    lambda resolved: self.resolver(
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/strawberry_django_plus/relay.py", line 1003, in resolver
    return self.resolve_connection(cast(Iterable[Node], nodes), info, **kwargs)
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/strawberry_django_plus/relay.py", line 1012, in resolve_connection
    return return_type.from_nodes(nodes, **kwargs)
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/strawberry_django_plus/relay.py", line 628, in from_nodes
    total_count = int(nodes.count())  # type:ignore
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 621, in count
    return self.query.get_count(using=self.db)
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 559, in get_count
    return obj.get_aggregation(using, ["__count"])["__count"]
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 544, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
Stack (most recent call last):
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/strawberry/schema/schema.py", line 226, in execute
    result = await execute(
  File "/Users/user/myapp/.venv/lib/python3.10/site-packages/strawberry/schema/execute.py", line 144, in execute
    process_errors(result.errors, execution_context)
```

I couldn't find any examples of connection field with async function. Could I have some guide on this?

Thanks!

My environment:

* Python 3.10
* django 4.1.6
* strawberry-graphql 0.156.3
* strawberry-graphql-django 0.9.2
* strawberry-django-plus 2.0.4

**Comment by devxoul** [comment]
I just realized that there is a connection for django. The issue is fixed with this change:

```diff
  @strawberry.type
  class Query:
-     @relay.connection
+     @gql.django.connection
      async def users(self) -> Iterable[UserNode]:
          return sync_to_async(User.objects.all)()
```

**Comment by bellini666** [comment]
Was going to mention exactly that to you, to use `gql.django.connection`! :)
