### ISSUE TITLE
Enabling the Django Debug Toolbar Integration raises AttributeError for `_djdt_cursor`

### ISSUE THREAD

**Issue by ZipBrandon** [blb-ventures/strawberry-django-plus#27]
I followed the instructions and to enable the DjDT integration and it raises an attribute error. I am using the current latest DjDT v3.2.4. DjDT works as expected when using its own middleware.

```
| Traceback (most recent call last):
|   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
|     response = get_response(request)
|   File "/usr/local/lib/python3.10/site-packages/strawberry_django_plus/middlewares/debug_toolbar.py", line 127, in __call__
|     response = super().__call__(request)
|   File "/usr/local/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 62, in __call__
|     panel.disable_instrumentation()
|   File "/usr/local/lib/python3.10/site-packages/debug_toolbar/panels/sql/panel.py", line 151, in disable_instrumentation
|     unwrap_cursor(connection)
|   File "/usr/local/lib/python3.10/site-packages/strawberry_django_plus/middlewares/debug_toolbar.py", line 109, in _unwrap_cursor
|     del c._djdt_cursor
|   AttributeError: _djdt_cursor
```

**Comment by bellini666** [comment]
Hey @ZipBrandon ,

Hrm, that's strange. Can you show me your list of middlewares?

**Comment by bellini666** [comment]
This should not be an issue anymore, specially after the latest release of django-debug-toolbar. Going to close the issue now, but please reopen it if that's not the case
