### ISSUE TITLE
Circular imports using LazyType seem to not work

### ISSUE THREAD

**Issue by kwongtn** [blb-ventures/strawberry-django-plus#89]
Consider the following code:

**./operation/schema/scalars.py**
```py
from strawberry_django_plus import gql

from operation import models

@gql.django.type(models.Vehicle)
class Vehicle:
    ...
    if TYPE_CHECKING:
        from spotting.schema.scalars import Event

    @gql.field
    def last_spottings(
        self, count: int = 1
    ) -> List[gql.LazyType["Event", "spotting.schema.scalars"]]:
        return spotting_models.Event.objects.filter(vehicle_id=self.id,).order_by(
            "-spotting_date"
        )[:count]
```

**./spotting/schema/scalars.py**
```py
from operation.schema.scalars import Vehicle

from spotting import models

@gql.django.type(models.Event)
class Event:
    vehicle: "Vehicle"
```

As you can see from the codes, both types refer to each other. Using usual `strawberry` and `strawberry_django` does not pose any problems, but it only has problems after migrating to `strawberry_django_plus`.

The following is the error logs:
```py
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/middlewares/debug_toolbar.py", line 149, in __acall__
    return await sync_to_async(self.process_request, thread_sensitive=False)(request)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/middlewares/debug_toolbar.py", line 152, in process_request
    response = super().__call__(request)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 48, in __call__
    if not show_toolbar(request) or DebugToolbar.is_toolbar_request(request):
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/debug_toolbar/toolbar.py", line 158, in is_toolbar_request
    resolver_match = request.resolver_match or resolve(
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/resolvers.py", line 649, in resolve
    for pattern in self.url_patterns:
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/rosak/urls.py", line 22, in <module>
    from .schema import schema
  File "/code/rosak/schema.py", line 5, in <module>
    from operation.schema.schema import OperationMutations, OperationScalars
  File "/code/operation/schema/schema.py", line 5, in <module>
    from operation.schema.scalars import Asset, Line, Station, Vehicle, VehicleType
  File "/code/operation/schema/scalars.py", line 123, in <module>
    class Vehicle:
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/type.py", line 398, in wrapper
    return _process_type(
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/type.py", line 282, in _process_type
    fields = list(_get_fields(django_type).values())
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/type.py", line 232, in _get_fields
    fields[name] = _from_django_type(django_type, name)

  # From here I narrowed down to guess that it is probably an issue with this library
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/type.py", line 118, in _from_django_type
    field = StrawberryDjangoField(
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django_plus/field.py", line 84, in __init__
    super().__init__(*args, **kwargs)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django/fields/field.py", line 61, in __init__
    self.is_auto = utils.is_auto(kwargs.get("type_annotation", None))
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django/utils.py", line 69, in is_auto
    return is_auto(obj)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry_django/fields/types.py", line 166, in is_auto
    return isinstance(type_, StrawberryAuto)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry/auto.py", line 60, in __instancecheck__
    return instance == "strawberry.auto"
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry/type.py", line 64, in __eq__
    return super().__eq__(other)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry/type.py", line 39, in __eq__
    resolved = StrawberryAnnotation(other).resolve()
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/strawberry/annotation.py", line 73, in resolve
    evaled_type = _eval_type(annotation, self.namespace, None)
  File "/usr/local/lib/python3.10/typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/local/lib/python3.10/typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'strawberry' is not defined

```

Help? 😅

Thanks 😁

**Comment by bellini666** [comment]
Hi @kwongtn :)

There was a change on `strawberry`'s side which broke how auto is checked. Are you using the latest version of this lib? Since [1.19.1](https://github.com/blb-ventures/strawberry-django-plus/releases/tag/v1.19.1) there should be a fix for that specific case.

**Comment by kwongtn** [comment]
Yes I am, here are my related dependency versions:
- strawberry-graphql: 0.121.0
- strawberry-graphql-django: 0.4.0
- strawberry-django-plus: 1.20.2

**Comment by bellini666** [comment]
@kwongtn it may be an issue with `strawberry-graphql-django` itself with its `is_auto` method.

There are 2 possibilities here that might fix your issue.

1) Try to use `gql.django.field` instead of `gql.field` for `last_spottings`

2) Try to use `strawberry.auto` instead of `gql.auto` for defining auto types. `gql.auto` is actually `strawberry.auto` now, but the way `strawberry` checks for it now, specially when using `from __future__ import annotations` messes auto checking when not using directly from it

Can you tell me if any of those (or even both) fixes your issue?

**Comment by kwongtn** [comment]
I've tried the strawberry solution (2) before, and it does not work.

Fortunately however, `gql.django.field` works! 🥳
Thank you so much for you help 😁 

Should I close this issue then? 🤔

**Comment by bellini666** [comment]
Awesome! :)

I'll close the issue then. I think `strawberry-graphql-django` itself needs a fix similar to the one I've done here. Will try to do that soon. But for your case, `gql.django.field` was the way to go even for some other reasons (it has better resolution for things like optimization, etc)
