### ISSUE TITLE
Relay.Node implementation broken after strawberry-graphql >= 0.118.2

### ISSUE THREAD

**Issue by oleo65** [blb-ventures/strawberry-django-plus#94]
After upgrading all strawberry dependencies some days ago, my previously working schema won't be running anymore. I get a `NameError` during startup of the django server with `name 'strawberry' is not defined`.

The stacktrace is somewhat wague about the location of the error but it seems to be ultimatetly very deep into the stdlib. My python skills somewhat ends there...

Trying to be as helpful as possible I have narrowed it down to specific strawberry-graphql releases.

* Working: 0.118.1 and below
* Broken: 0.118.2 and above

The release notes state something with `strawberry.auto` and annotations and seem related to me but I honestly have no idea how to tackle this.

I put together a minimum example model from my app, stripping most non needed parts.

```python
import strawberry
from strawberry_django_plus import gql
from django.contrib.auth import get_user_model

@gql.django.type(get_user_model())
class UserNode(gql.relay.Node):
    last_name: gql.auto
    is_superuser: gql.auto

    @strawberry.field
    def avatar_url(self, root) -> str | None:
        return root.avatar_url
```

If I change the return type of the custom field `avatar_url` to non nullable (`str`), the schema runs successfully. I also experienced this behaviour with custom node types and not only primitive value types.

If I change the `UserNode` to a non Relay implementation, the schema also runs successfully which made me suspect this library in the first place. 😉 

```python
@strawberry.django.type(get_user_model())
class UserNode():
    last_name: gql.auto
    is_superuser: gql.auto

    @strawberry.field
    def avatar_url(self, root) -> str | None:
        return root.avatar_url
```

If changing the custom field `avatar_url`  to `@gql.django.field` the schema also runs successfully. But I don't quite understand why I must use the custom field implementation of this library for a nullable (primitive) field which does not have any dependencies on django (it is a simple property on the model class).

Please let me know if I can be of any more help here. Thanks :)

<details><summary>Stacktrace</summary>
<p>

```
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/channels/management/commands/runserver.py", line 75, in inner_run
    self.check(display_num_errors=True)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ole/repos/investor/Investor/Investor/urls/__init__.py", line 1, in <module>
    from .urls import *
  File "/home/ole/repos/investor/Investor/Investor/urls/urls.py", line 17, in <module>
    path('', include('graphql_api.urls.graphql')),
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ole/repos/investor/Investor/graphql_api/urls/graphql.py", line 4, in <module>
    from graphql_api.views import ApiSchema
  File "/home/ole/repos/investor/Investor/graphql_api/views.py", line 6, in <module>
    from .schema.schema import schema
  File "/home/ole/repos/investor/Investor/graphql_api/schema/schema.py", line 19, in <module>
    from .models.user import UserMutation, UserQuery
  File "/home/ole/repos/investor/Investor/graphql_api/schema/models/user.py", line 80, in <module>
    class UserNode(gql.relay.Node):
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry_django_plus/type.py", line 398, in wrapper
    return _process_type(
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry_django_plus/type.py", line 282, in _process_type
    fields = list(_get_fields(django_type).values())
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry_django_plus/type.py", line 232, in _get_fields
    fields[name] = _from_django_type(django_type, name)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry_django_plus/type.py", line 118, in _from_django_type
    field = StrawberryDjangoField(
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry_django_plus/field.py", line 84, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry_django/fields/field.py", line 61, in __init__
    self.is_auto = utils.is_auto(kwargs.get("type_annotation", None))
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry_django/utils.py", line 69, in is_auto
    return is_auto(obj)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry_django/fields/types.py", line 166, in is_auto
    return isinstance(type_, StrawberryAuto)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry/auto.py", line 60, in __instancecheck__
    return instance == "strawberry.auto"
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry/type.py", line 64, in __eq__
    return super().__eq__(other)
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry/type.py", line 39, in __eq__
    resolved = StrawberryAnnotation(other).resolve()
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.10/site-packages/strawberry/annotation.py", line 73, in resolve
    evaled_type = _eval_type(annotation, self.namespace, None)
  File "/usr/lib/python3.10/typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/lib/python3.10/typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'strawberry' is not defined
```

</p>
</details>

**Comment by bellini666** [comment]
Hi @oleo65 , this is very similar to the case in here: https://github.com/blb-ventures/strawberry-django-plus/issues/89

If you read my comments there, I thought it was something that should be fixed on `Strawberry-graphql-django`, but maybe it is something in here... I'll take a closer look at this!

> But I don't quite understand why I must use the custom field implementation of this library for a nullable (primitive) field which does not have any dependencies on django (it is a simple property on the model class).

Actually, it is always better to use `gql.django.field` for any model related types. That custom field has some optimizations for fetching the model attribute while handling sync and async stuff. Also, if you enabled the [query optimizer extension](https://blb-ventures.github.io/strawberry-django-plus/query-optimizer/), accessing `avatar_url` would trigger an extra query to the database. You can make sure that the field is also selected for custom resolvers by defining it with:

```python
@gql.django.field(only=["avatar"])
def avatar_url(self, root) -> str | None:
    return root.avatar_url
```

Considering that `avatar_url` is a property that returns the url from an `ImageField` defined as `avatar` at the user model.

You can even use a [model property](https://blb-ventures.github.io/strawberry-django-plus/query-optimizer/#model-property) for that and define `avatar_url: auto` at the type for simplification.

**Comment by bellini666** [comment]
@oleo65 I just contributed a change to strawberry which [just got released](https://github.com/strawberry-graphql/strawberry/releases/tag/0.123.3) that should fix this issue.

I'll close the issue as it should be solved. But please tell me if that is not the case

**Comment by oleo65** [comment]
Thanks for your fast support here. I did not have the chance to verify the changes but nevertheless can confirm that using `@gql.django.field` is working well. 👍
